### PR TITLE
Some improvements

### PR DESCRIPTION
**Pull request by apexmin**
UI for Scrcpy arguments input added
Fixed crahes when ADB errors occured at starting Scrcpy
Removed MVVM framework for portability
Terminating process improvement

### CODE REVIEW

**Comment by IkeRolfe** [comment]
Thanks again @apexmin wish I had more time to work on this.

**Comment by IkeRolfe** [comment]
@apexmin do you have a use case for displaying 2 devices On the same window?  I am thinking about enumerating the connected devices and having a selection of which one to display.
For multiple devices a second window could be launched.

**Comment by apexmin** [comment]
> @apexmin do you have a use case for displaying 2 devices On the same window? I am thinking about enumerating the connected devices and having a selection of which one to display.
> For multiple devices a second window could be launched.

Yeah. I am trying to build an app for a specific scenario which is testing between 2 devices wireless. Also I want it implemented in the app itself so that's why I called alignPanel immediately and prefer implemented window rather than an independent one. I altered it pretty much all I need, so you can list devices and do more things. Thank you for such a good job at the first point. I really needed this project. Thanks again.

**Comment by IkeRolfe** [comment]
@apexmin your very much welcome.  I was a bit surprised someone jumped on this so quickly, and a little concerned about the half-baked code that I published.  But I see you found your way around.  I really like like the changes you have done.  Pulling Caliburn Micro was a good call, especially since the workflow is so UI drivin there is no reason to implement MVVM.  In the end it will just complicate things.  

I am going to a sprint tonight, feel free let me know if you if you see any issues with these updates:
- [ ] Enumerate all connected devices and consolidate session management to support more than 2 devices.
- [ ] Display devices in a snappable child window.
- [ ] Theme changer, just because it's easy and fun.
- [ ] Create UI controls to simplify common command line arguments.
- [ ] Create file dialogue for for recording path.
- [ ] Add adb and scrcpy to source and make paths optional.
- [ ] Attach and read adb debug with output.

Let me know if you have anymore ideas for this app.

My original use case is a little different, facilitate training end users on new apps and attaching the adb output to the session so I can play backlogs along with the recording session (that one is a ways out).
However am excited about building something useful to others.  Here was my original roadmap for the app.
1. Build UI for presenting apps and recording sessions.
2. Remove scrcpy, go directly to adb, and replicate needed functions (capture, record, control)
3. Capture adb events and timestamps
4. Play back recordings with adb output to see how events and errors effect actual user experience

**Comment by apexmin** [comment]
@IkeRolfe  I guess there are no issues at all for your prospected updates and I like all of them, especially the last two. Your roadmap seems to be really amazing too. Actually I just got to start on C#, WPF so I have very little knowledge and I was worried I might change the project not based on your concept but glad if you liked it. . 👍 I want to also do the second one on your roadmap, but it was hard to me. I hope this develops well.

**Pull request merged**
